[project]
name = "notebooklm-clone"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "assemblyai>=0.44.3",
    "yt-dlp>=2025.11.12",
]
